environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.5/julia-0.5-latest-win32.exe"
  - JULIAVERSION: "julialang/bin/winnt/x64/0.5/julia-0.5-latest-win64.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/yuyichao/FunctionWrappers.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(pwd(), \"LINQ\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"DataFrames\", \"nl/nullable\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"WeakRefStrings\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"TypedTables\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"SQLite\")"
  - cd ~\.julia\v0.5\DataStreams & git checkout c46a5a1bb207a38d604be5bf8a8ab43474de04c8
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.build(\"LINQ\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"LINQ\")"
