site_name: Query.jl
repo_url: https://github.com/davidanthoff/Query.jl
site_description: Query framework for julia
site_author: davidanthoff

theme: material

extra:
  palette:
    primary: 'indigo'
    accent: 'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
